Add DummyFinder
eggplants/wbsv-cli pull request #52
Opened 2020-05-22 13:51 UTC by yswallow

Add DummyFinder and some options.

This makes test easier.

2020-05-27 08:26 UTC, eggplants commented on wbsv/ParseArgs.py
> +                        help='Run without waiting (-d, -f only).')
This newly-added part means:
- for testing, make program search within dummy sites
- when retrying and finding links, run without wait
It is true?

2020-05-27 08:28 UTC, eggplants commented on wbsv/ParseArgs.py
> +                        help='Run without waiting (-d, -f only).')
And please get rid of `default=False,` .
`action='store_true'` sets false to flag by default.

2020-05-27 08:34 UTC, eggplants commented on wbsv/Find.py
> +        time.sleep(randint(2, 5))
This parameter seem too long...
I'd like to be shorter or let users set it up as they wish.

2020-05-27 08:34 UTC, eggplants requested changes
Please check my comment... Sorry for my late.

2020-05-27 09:19 UTC, yswallow commented
I think the waiting is not too long. 

I close this.

2020-05-27 14:17 UTC, eggplants commented on wbsv/Find.py
> +        time.sleep(randint(2, 5))
OK, I manage to accept its latency...

2020-05-27 14:18 UTC, eggplants reviewed
Please fix about only options' flags only.

2020-05-27 16:16 UTC, eggplants commented
![image](https://user-images.githubusercontent.com/42153744/83045663-d8190d80-a080-11ea-95d2-00359ebf05ca.png)

2020-05-31 10:00 UTC, yswallow commented
日本語で失礼します。

-d (--dry_run), -f (--fake_fetch), -n (--no_wait)についてどのような挙動がご希望でしょうか。 
`action='store_true'`のみで( `default=False`を消すということで)よろしいでしょうか。

日本語で失礼しました。

2020-05-31 13:12 UTC, eggplants commented
>-d (--dry_run), -f (--fake_fetch), -n (--no_wait)についてどのような挙動がご希望でしょうか。
>action='store_true'のみで( default=Falseを消すということで)よろしいでしょうか。
そうです

2020-05-31 15:40 UTC, merged

2020-05-31 15:41 UTC, eggplants commented
Thank you for your contribution...! I appreciate your help.